human_walking_positions: [-68.12, -296.93, -0.62,
                          -70.60, -306.93, -0.73,
                          -72.32, -313.85, -0.83,
                          -69.03, -286.93, -0.36, 
                          -60.30, -288.71, -0.42,
                          -67.54, -319.47, -0.88,
                          -82.44, -316.79, -0.76,
                          -60.55, -278.18, -0.30,
                          -71.10, -277.59, -0.21] #[x, y, z]
number_of_humans: 9 
human:
  size: [0.55, 0.9, 1.9]
  
  offset: [0, 0, 0.95] #[x, y, z]
